import requests

headers = {
    'Accept-Encoding': 'gzip, deflate, br',
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Connection': 'keep-alive',
    'DNT': '1',
    'Origin': 'https://qa-aws01webql.cnbc.com',
}

data = '{"query":"# Write your query or mutation here\\n# Write your query or mutation here\\n{\\npage(\\n path:\\"/us-top-news-and-analysis\\") {\\n brand\\n layout {\\n   columns {\\n     span\\n     modules {\\n       name\\n       source\\n       attributes\\n      serverRenderPolicy\\n       data {\\n          ...on heroLedePlusThree {\\n  id\\n  assets {\\n    id\\n    type\\n    premium\\n    description\\n    brand\\n    title\\n    headline\\n    shorterDescription\\n    section {\\n      eyebrow\\n      url\\n    }\\n    url\\n    promoImage {\\n      id\\n      url\\n    }\\n    premium\\n    dateLastPublishedSixHr\\n  }\\n}\\n         ...on articleHeader{\\n           author{\\n             name\\n           }\\n           sourceOrganization{\\n             name\\n           }\\n           datePublished\\n dateModified\\n dateLastPublished\\n dateFirstPublished\\n datePublishedFormatted\\n dateLastPublishedFormatted\\n         }\\n         ... on articleBody {\\n           id\\n           type\\n           brand\\n           premium\\n           section {\\n             id\\n             color\\n           }\\n           native\\n           creatorOverwrite\\n           sourceOrganization {\\n             id\\n             url\\n             name\\n             logo\\n             creatorOverwrite\\n             linkHeadline\\n           }\\n           body {\\n             content {\\n               tagName\\n               attributes\\n               children\\n             }\\n           }\\n           shortestHeadline\\n           featuredMedia {\\n             id\\n             ... on image {\\n               caption\\n               copyrightHolder\\n               isHighTouch\\n             }\\n           }\\n         }\\n         ... on featuredBreaker {\\n           url\\n           type\\n           title: eyebrow\\n           subType\\n           sectionLabel\\n           showTime\\n           logo {\\n             url\\n           }\\n           shorterHeadline\\n           assets(count: 8, promoted: true) {\\n             ... on event {\\n               startDate\\n               location\\n             }\\n             id\\n             brand\\n             type\\n             native\\n             url\\n             datePublished\\n             title\\n             linkHeadline\\n             shorterHeadline\\n             slug\\n             subType\\n             section {\\n               subType\\n             }\\n             sectionHierarchy {\\n               tagName\\n             }\\n             promoImage {\\n               id\\n               url\\n             }\\n             author {\\n               name\\n             }\\n             sourceOrganization {\\n               name\\n             }\\n             creatorOverwrite\\n           }\\n         }\\n       }\\n     }\\n   }\\n }\\n}\\n}"}'

response = requests.post('https://qa-aws01webql.cnbc.com/graphql', headers=headers, data=data)
print(response.json())